import type { Detector } from '../types';
import { createFinding } from './helpers';

const DEFAULT_TITLE = /^(?:create next app|next\.js(?: app)?|react app|vite \+ (?:lit|preact|react|solid|svelte|vue)(?: \+ ts)?)$/i;
const DEFAULT_DESCRIPTION = /^(?:generated by create next app|vite \+ (?:lit|preact|react|solid|svelte|vue)(?: template)?)$/i;
const PLACEHOLDER_VALUE = /(?:\b(?:localhost|todo|tbd)\b|127\.0\.0\.1|0\.0\.0\.0|example\.(?:com|org|net)|lorem ipsum|replace[-_ ]?(?:me|this)|your[-_ ]?(?:app|description|image|site|title))/i;

const displayUrl = (value: string): string => {
  try {
    const url = new URL(value);
    return `${url.hostname}${url.pathname}`;
  } catch {
    return value.slice(0, 140);
  }
};

const hostname = (value: string): string | undefined => {
  try {
    return new URL(value).hostname.toLowerCase().replace(/^www\./, '');
  } catch {
    return undefined;
  }
};

const defaultFavicon = (value: string): boolean => {
  try {
    return /\/(?:next|vercel|vite)\.svg$/i.test(new URL(value).pathname);
  } catch {
    return /(?:^|\/)(?:next|vercel|vite)\.svg$/i.test(value);
  }
};

export const metadataDetectors: Detector[] = [
  {
    id: 'framework-metadata-residue',
    category: 'template',
    analyze(context) {
      if (!context.isEntryPage) return [];
      const evidence: string[] = [];
      const title = context.title?.trim() ?? '';
      const description = context.metadata.description?.trim() ?? '';
      const generator = context.metadata.generator?.trim() ?? '';
      const defaultIcons = context.metadata.faviconUrls.filter(defaultFavicon);
      let hasTextResidue = false;

      if (DEFAULT_TITLE.test(title)) {
        hasTextResidue = true;
        evidence.push(`Default document title: “${title}”`);
      }
      if (DEFAULT_DESCRIPTION.test(description)) {
        hasTextResidue = true;
        evidence.push(`Default meta description: “${description}”`);
      }
      if (/create next app|create-vite/i.test(generator)) {
        hasTextResidue = true;
        evidence.push(`Scaffold generator metadata: “${generator}”`);
      }
      for (const [label, value, pattern] of [
        ['Open Graph title', context.metadata.openGraph['og:title'], DEFAULT_TITLE],
        ['Open Graph description', context.metadata.openGraph['og:description'], DEFAULT_DESCRIPTION],
        ['Twitter title', context.metadata.twitter['twitter:title'], DEFAULT_TITLE],
        ['Twitter description', context.metadata.twitter['twitter:description'], DEFAULT_DESCRIPTION],
      ] as const) {
        if (value && pattern.test(value.trim())) {
          hasTextResidue = true;
          evidence.push(`Default ${label}: “${value.trim()}”`);
        }
      }
      evidence.push(...defaultIcons.slice(0, 3).map((url) => `Framework favicon: ${displayUrl(url)}`));
      if (!evidence.length) return [];

      return [createFinding(
        this.id,
        this.category,
        'The scaffold survived deployment',
        'Framework starter metadata remains visible on the published portfolio instead of being replaced with site-specific identity.',
        hasTextResidue ? 5 : 4,
        evidence,
      )];
    },
  },
  {
    id: 'metadata-neglect',
    category: 'template',
    analyze(context) {
      if (!context.isEntryPage) return [];
      const { metadata } = context;
      const missing: string[] = [];
      if (!context.title?.trim()) missing.push('document title');
      if (!metadata.description) missing.push('meta description');
      if (!metadata.faviconUrls.length) missing.push('favicon');
      if (!metadata.canonicalUrl) missing.push('canonical URL');
      const missingOpenGraph = ['og:title', 'og:description', 'og:image'].filter((key) => !metadata.openGraph[key]);
      if (missingOpenGraph.length) missing.push(`Open Graph fields (${missingOpenGraph.join(', ')})`);

      const values = [
        ['title', context.title],
        ['description', metadata.description],
        ['canonical', metadata.canonicalUrl],
        ...Object.entries(metadata.openGraph),
        ...Object.entries(metadata.twitter),
      ] as Array<[string, string | undefined]>;
      const problems = values
        .filter(([, value]) => value && PLACEHOLDER_VALUE.test(value))
        .map(([key, value]) => `${key} contains placeholder value: “${value!.slice(0, 100)}”`);
      const pageHost = hostname(context.finalUrl);
      for (const [label, value] of [['canonical', metadata.canonicalUrl], ['og:url', metadata.openGraph['og:url']]] as const) {
        const metadataHost = value ? hostname(value) : undefined;
        if (pageHost && metadataHost && pageHost !== metadataHost) {
          problems.push(`${label} points to ${metadataHost} instead of ${pageHost}`);
        }
      }
      const ogImage = metadata.openGraph['og:image'];
      if (ogImage && !/^https?:\/\//i.test(ogImage)) problems.push('og:image is not an absolute HTTP(S) URL');

      if (!problems.length && missing.length < 3) return [];
      const points = problems.length ? 3 : missing.length >= 4 ? 2 : 1;
      return [createFinding(
        this.id,
        this.category,
        problems.length ? 'Placeholder metadata escaped containment' : 'Metadata finishing pass not found',
        problems.length
          ? 'Published metadata contains placeholder or mismatched values that were not reconciled with the deployed site.'
          : 'Several basic identity and link-preview fields are absent, suggesting the publishing scaffold never received a finishing pass.',
        points,
        [...problems.slice(0, 6), ...missing.slice(0, 5).map((field) => `Missing ${field}`)],
      )];
    },
  },
];
